### ISSUE TITLE
Class L5Modular not found

### ISSUE THREAD

**Issue by thegr8dev** [Artem-Schander/L5Modular#62]
**Describe the bug**
Installed this package on clean laravel 8.12 and jsut make a new module call Faq. 

After this I just go to https://l5modular.com/usage/#facade

and using first one 

`L5Modular::exists('HelloWorld');`

and it give me following error

Error
Class 'L5Modular' not found
http://localhost:8000/test/

**To Reproduce**
1. Install new laravel and this package.
2. Make any module after setup the package.
3. Make a test route and use any facade from docs or the exists() one.
4. You will get class not found error.

**Expected behavior**
It should return true or false as per docs.

**Screenshots**

![image](https://user-images.githubusercontent.com/33778557/116685284-b54d5280-a9cf-11eb-8cda-4509a7c5838a.png)

**Environment (please complete the following information):**
 - OS & version: Windows 10 Build 19042
 - Laravel version: 8.12
 - L5Modular version: 2.1

**Comment by Artem-Schander** [comment]
Hi @thegr8dev,
Thank you for raising this issue. I will look into it as soon as possible.

**Comment by Standin-Alone** [comment]
any updates?

**Comment by Artem-Schander** [comment]
I'm sorry that I let you wait that long. I'm currently really busy but I think I will be able to find some time this weekend.

**Comment by Standin-Alone** [comment]
Thank you sir. You are very kind. :)

**Comment by Artem-Schander** [comment]
I have just published the [patch](https://github.com/Artem-Schander/L5Modular/releases/tag/2.1.1)
Let me know, if there is still something wrong.

**Comment by Standin-Alone** [comment]
still not working undefined. L5modular not found

**Comment by Standin-Alone** [comment]
the module that disabled still accessible

**Comment by Artem-Schander** [comment]
Dis you disabled it in the config file, or by `SomeModule::disable()`?

**Comment by Standin-Alone** [comment]
i put this code L5Modular::disable('Modulename');  and my module still not disable. i can still access the module
